- name: Ensure directory is available
  file:
    path: "{{ jobconf_directory }}"
    state: directory
    owner: "{{ jobconf_user }}"
    group: "{{ jobconf_group }}"
    mode: 0750

- name: Clone repo
  become: true
  become_user: "{{ jobconf_user }}"
  git:
    repo: 'https://github.com/usegalaxy-eu/jcaas/'
    dest: "{{ jobconf_directory }}"
    version: "{{ jobconf_version }}"
  register: repo

- name: Send templates
  template:
    src: "{{ item }}"
    dest: "{{ jobconf_config_directory }}/{{ item }}"
    owner: "{{ jobconf_user }}"
    group: "{{ jobconf_group }}"
    mode: 0640
  with_items:
    - conf.yaml
    - destination_specifications.yaml
    - tool_destinations.yaml
  register: jobconf_tpl

- name: Send runner script
  template:
    src: "run.sh"
    dest: "{{ jobconf_directory }}/run.sh"
    owner: "{{ jobconf_user }}"
    group: "{{ jobconf_group }}"
    mode: 0750
  register: jobconf_runner

- name: Install all of the necessary dependencies
  become: true
  become_user: "{{ jobconf_user }}"
  pip:
    virtualenv: "{{ jobconf_venv }}"
    virtualenv_command: "{{ jobconf_venv }}/bin/virtualenv"
    requirements: "{{ jobconf_directory }}/requirements.txt"
  register: jobconf_dep

- name: "Restart jobconf process"
  shell: "{{ jobconf_supervisord }} restart job_conf_service"
  when: (repo.changed or jobconf_tpl.changed or jobconf_runner.changed or jobconf_dep.changed) and (jobconf_supervisord is defined)
